/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJni */

#ifndef _Included_HelloJni
#define _Included_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJni
 * Method:    getStringFromCStatic
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJni_getStringFromCStatic
  (JNIEnv *, jclass);

/*
 * Class:     HelloJni
 * Method:    getStringFromCNonStatic
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJni_getStringFromCNonStatic
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJni_accessField
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJni_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJni_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJni_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_HelloJni_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    accessUTFChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJni_accessUTFChars
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
